version: '3'

services:
  reports:
    build: .
    volumes:
      - $HOME/.config/gcloud:/home/reports/.config/gcloud
      - $PWD:/home/reports/
    ports:
      # To run container jupyter notebooks on the host
      - 8891:8891
      # To access the website via host port 8000 when completed
      - 8000:8000
    environment:
      # Set the service key path for calitp-py
      #- CALITP_SERVICE_KEY_PATH=/home/reports/.config/gcloud/application_default_credentials.json
      # Set the GCP Bigquery max bytes value - needs to be larger than the calitp-py default
      - CALITP_BQ_MAX_BYTES=20000000000
