name: Build and deploy website to GCS

on:
  workflow_dispatch:
    inputs:
      site_target:
        description: 'Deploy to development or production Reports site? (must deploy to development first)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Install python packages
      run: |
        pip install -r requirements.txt
    - name: Install node packages
      run: npm install
      working-directory: website
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Run data ----
    - name: Run report data
      if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.site_target == 'dev')}}
      working-directory: reports
      run: |
        make parameters
        make data

    # copy data ----
    - name: Copy development report data to GCS
      if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.site_target == 'dev')}}
      run: |
        gsutil -m rsync -r reports/outputs/ gs://test-calitp-reports-data/report_gtfs_schedule/
    - name: Copy production report data to GCS and local
      if: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && inputs.site_target == 'prod')}}
      run: |
        gsutil -m rsync -r gs://test-calitp-reports-data/report_gtfs_schedule/ gs://calitp-reports-data/report_gtfs_schedule/
        gsutil -m rsync -r gs://calitp-reports-data/report_gtfs_schedule/ reports/outputs/

    - name: Install Netlify CLI
      run: npm install --location=global netlify-cli@17.x.x
    # build ----
    - name: Build website
      run: npm run build
      working-directory: website

    # Deploy to Netlify ----
    - name: Deploy to Netlify (Development)
      if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.site_target == 'dev')}}
      run: |
        netlify deploy \
            --alias="${GITHUB_REPOSITORY#*/}-${{ github.event.number }}" \
            --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --dir="./website/build" \
            --site=${{ secrets.NETLIFY_PREVIEW_APP_SITE_ID }}
    - name: Deploy to Netlify (Production)
      if: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && inputs.site_target == 'prod')}}
      run: |
        netlify deploy \
            --prod
            --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --dir="./website/build" \
            --site=cal-itp-reports
