name: Build and deploy to Netlify

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install python packages
      run: |
        pip install -r requirements.txt
    - name: Install node packages
      run: npm install
      working-directory: website
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # copy data ----
    - name: Copy development report data
      if: ${{ github.event_name == 'push' }}
      run: |
        gsutil -m rsync -r gs://gtfs-data-test/report_gtfs_schedule/ reports/outputs/
    - name: Copy production report data
      if: ${{ github.event_name == 'tag' }}
      run: |
        gsutil -m rsync -r gs://gtfs-data/report_gtfs_schedule/ reports/outputs/

    # build ----
    - name: Build
      run: npm run build
      working-directory: website

    # deploy ----

    - name: Deploy development to Netlify
      if: ${{ github.event_name == 'push' }}
      run: |
        npm install netlify-cli
        netlify deploy --site=cal-itp-reports --dir=./website/build --alias=test
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    - name: Deploy production to Netlify
      if: ${{ github.event_name == 'tag' }}
      run: |
        npm install netlify-cli
        netlify deploy --site=cal-itp-reports --dir=./website/build
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
