name: Test and Lint

on:
  push:

jobs:
  lint:
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0

  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run data tests
        working-directory: ./tests
        run: python test_report_data.py
      - name: Prepare website build
        run: cp -r tests/outputs/2022 reports/outputs/. && cp tests/fixtures/* reports/outputs/.
      - name: Run website build
        working-directory: ./website
        run: npm install && npm run build && cat build/index.html | grep "Monthly GTFS Quality Reports"

      # if tests succeed and we're on a PR, publish just the test data to Netlify
      - name: Deploy docs preview to Netlify
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          npm install -g netlify-cli
          netlify deploy --dir=docs/_build/html --alias=${GITHUB_REPOSITORY#*/}-${PR_NUMBER}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}

      - uses: peter-evans/find-comment@v2
        if: ${{ github.event_name == 'pull_request' }}
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: --cal-itp-previews.netlify.app

      - uses: peter-evans/create-or-update-comment@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: "Preview url: https://${{github.event.repository.name}}-${{ github.event.number }}--cal-itp-previews.netlify.app"
          edit-mode: replace
